name: CI

on:
  release:
    types: [published]
  
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
        echo SHA is $GITHUB_SHA	
        echo REF is $GITHUB_REF
        sudo apt install git-buildpackage
        gbp clone --debian-branch=debian/sid https://github.com/grandpaul/BerryNet.git
        cd BerryNet
        ls
