name: CI

on:
  release:
    types: [published]
  
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
        echo SHA is $GITHUB_SHA	
        echo REF is $GITHUB_REF
        sudo apt-get -y update
        sudo apt-get -y install git-buildpackage
        sudo apt-get -y install build-essential devscripts
        sudo apt-get -y install lsb-release
        sudo apt-get -y install debhelper dh-apache2 dh-python git python3 python3-setuptools
        sudo apt-get -y install pristine-tar
        lsb_release -a
        curl -sL https://raw.githubusercontent.com/DT42/BerryNet-repo/master/setup.sh | sudo -E bash
        sudo apt-get -y install freeboard
        git remote add github1 https://github.com/grandpaul/BerryNet.git
        git remote update
        git branch -a
        git checkout github1/upstream -b upstream
        git checkout github1/pristine-tar -b pristine-tar
        git checkout github1/debian/sid -b debian/sid
        gbp buildpackage --no-sign
        #uscan --verbose
        #VER1=`ls ../berrynet_*.orig.tar.gz | sed 's/.*berrynet_//' | sed 's/.orig.tar.gz//'`
        #echo VER1 is $VER1
        #cd ..
        #cd berrynet-$VER1
        #debuild
