name: CI

on:
  release:
    types: [published]
  
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
        echo SHA is $GITHUB_SHA	
        echo REF is $GITHUB_REF
        sudo apt install git-buildpackage
        git remote add github1 https://github.com/grandpaul/BerryNet.git
        git remote update
        git branch -a
        git checkout github1/upstream -b upstream
        git checkout github1/pristine-tar -b pristine-tar
        git checkout github1/debian/sid -b debian/sid
        uscan --verbose
